[package]
name = "usbrelay-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.2", features = ["derive"] }
clap_derive = "4.5.0"
libftdi1-sys = { version = "1.1.3", default-features = false }
