name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  rust-ci:
    uses: charlieh0tel/deb-workflows/.github/workflows/rust-ci.yml@v1
    with:
      build-deps: "libftdi1-dev"
      # so clippy sees the tests too
      check-args: "--all-targets"
